name: Ubuntu

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [master-dev]

jobs:
  build:
    if: github.repository_owner == 'grame-cncm' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install libcurl
        run: |
          sudo apt-get update -qq 
          sudo apt-get install libcurl4-openssl-dev

      - name: Install libmicrohttpd
        run: |
          sudo apt-get update -qq 
          sudo apt-get install libmicrohttpd-dev

      - name: Build Faust
        run: make