name: Windows

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master-dev ]
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'grame-cncm' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Install vcpkg
        uses: lukka/run-vcpkg@v7

      - name: Install libcurl
        run: |
          vcpkg install curl:x64-windows
          vcpkg integrate install

      - name: Build Faust
        run: |
          make -C build cmake BACKENDS=regular.cmake TARGETS=win-ci.cmake ADDITIONAL_CMAKE_FLAGS="-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
          make -C build